name: Docker Deployment
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Deploy with SSH
        run: |
          ssh root@5.23.54.98> << EOF
            cd /opt/app-backend/Backend
            docker compose up -d --build
            docker image prune
          EOF
